source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target 'ImageValet_Example', :exclusive => true do
  pod "ImageValet", :path => "../"
end

target 'ImageValet_Tests', :exclusive => true do
  pod "ImageValet", :path => "../"
  
  pod "Nimble"  
end
