source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

abstract_target 'import_pods' do
  pod "ImageValet", :path => "../"
  pod "Alamofire"
  pod "AlamofireImage", :git => 'https://github.com/Alamofire/AlamofireImage', :branch => 'master'

  target 'ImageValet_Example' do

  end

  target 'ImageValet_Tests' do
    pod "Nimble", :git => 'https://github.com/Quick/Nimble', :branch => 'swift-3.0'
  end
end
